import { createElement } from 'lwc';
import Bill_To_OrderSummeryAddress from 'c/bill_To_OrderSummeryAddress';

describe('c-bill-to-order-summery-address', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-bill-to-order-summery-address', {
            is: Bill_To_OrderSummeryAddress
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});