import { createElement } from 'lwc';
import Ship_to_OrderSummaryAddress from 'c/ship_to_OrderSummaryAddress';

describe('c-ship-to-order-summary-address', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-ship-to-order-summary-address', {
            is: Ship_to_OrderSummaryAddress
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});